---
name: Automation Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CD Build
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      # echo "$DOCKER_TOKEN" | docker login registry.gitlab.com --username "$DOCKER_USER" --password-stdin
      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install Testing Requirements
        run: sudo pip install -r requirements-test.txt

      - name: Lint
        run: openwisp-qa-check --skip-checkmigrations

      - name: Setup
        run: |
          echo "127.0.0.1 dashboard.openwisp.org api.openwisp.org wireguard-updater.openwisp.org" |
          sudo tee -a /etc/hosts

      - name: Build & Publish
        run: make publish TAG=edge || (docker-compose logs && exit 1)
        env:
          SELENIUM_HEADLESS: 1
