---
name: Deploy container images

on: workflow_dispatch

jobs:
  build:
    name: CD Build
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Testing Requirements
        run: sudo pip install -r requirements-test.txt

#      - name: Lint
#        run: openwisp-qa-check --skip-checkmigrations

      - name: Setup
        run: |
          echo "127.0.0.1 dashboard.openwisp.org api.openwisp.org" | sudo tee -a /etc/hosts

      # the following action is equivalent to
      # echo "$DOCKER_HUB_SECRET" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: false
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build & Publish to Docker Hub
        if: false
        run: |
          make publish TAG=edge USER=registry.docker.com/openwisp || (docker-compose logs && exit 1)
        env:
          SELENIUM_HEADLESS: 1

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Skip image builds and tests since they were done when
      # publishing to Docker Hub
      - name: Build & Publish to GitLab Container Registry
        run: |
          make base-build
          make publish TAG=edge SKIP_BUILD=false SKIP_TESTS=true
